config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords], controllers: { #skipで使わないルーティング削除
    sessions: "admin/sessions"
  }

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  #会員側の設定
  root 'public/homes#top'
  get 'about', to: 'public/homes#about'

  devise_scope :customer do #ゲストログイン機能
    post 'customer/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  scope module: :public do
    resources :cooking_posts, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      collection do #オリジナルのアクションに対する設定
        get 'search' #キーワード検索のアクション
      end
    end
    resources :food_strage_areas, only: [:index]
    resources :home_foods, only: [:new, :create, :index, :edit, :update, :destroy] do
      collection do
        get 'genre_search' #ジャンル検索のアクション
      end
    end

    get '/notifications/:id/mark_as_read' => 'notifications#mark_as_read', as: "mark_as_read_notifications" #URIパターンを設計書通りに修正
    resources :notifications, only: [:index, :destroy]

    get '/customers' => 'customers#index'
    get '/customers/my_page' => 'customers#show'
    get '/customers/information/edit' => 'customers#edit'
    patch '/customers/information' => 'customers#update'
    get '/customers/:id/cooking_posts' => 'customers#posts_index', as: "posts_index_customers"
    get '/customers/check' => 'customers#check'
    patch '/customers/out' => 'customers#out'
    get '/customers/search' => 'customers#search' #キーワード検索のアクション
  end

  #管理者側の設定
  get 'admin', to: 'admin/homes#top'
  namespace :admin do
    resources :genres, only: [:index, :destroy, :create, :edit, :update]
    resources :food_strage_areas, only: [:new, :create, :index, :destroy, :edit, :update]
    resources :cooking_posts, only: [:index, :show]

    get 'customers/:id/cooking_posts' => 'customers#posts_index', as: "customers_posts_index"
    resources :customers, only: [:show, :edit, :update]
  end

end

app/models/cooking_post.rb
class CookingPost < ApplicationRecord

  #アソシエーション
  belongs_to :customer

  has_one_attached :cooking_post_image

  #バリデーション設定
  validates :name, presence: true
  validates :introduction, presence: true
  #gem追加後の画像におけるバリデーション設定
  validates :cooking_post_image, content_type: { in: ['image/jpg', 'image/jpeg', 'image/png'] } #画像の拡張子を制限
  validates :cooking_post_image, size: { less_than: 5.megabytes } #画像のサイズを制限

  #画像の設定メソッド
  def get_cooking_post_image(width, height)
    unless cooking_post_image.attached? #投稿に画像がない場合
      file_path = Rails.root.join('app/assets/images/no_image.jpg') #()内へのルートパス作成
      cooking_post_image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg') #imageに画像を代入
    end
    cooking_post_image.variant(resize_to_fill: [width, height]).processed #指定された幅と高さにリサイズされたデフォルト画像が代入されたcooking_post_imageを返す
  end

end

app/controllers/admin/cooking_posts_controller.rb
class Admin::CookingPostsController < ApplicationController

  #管理者ログイン前ユーザーによるURL直打ちでの、ページ遷移と処理を制限（全てのアクションに対し）
  before_action :authenticate_admin!

  def index
    @cooking_posts = CookingPost.all.page(params[:page]).per(10)
  end

  def show
    @cooking_post = CookingPost.find(params[:id])
    @customer = @cooking_post.customer
  end
end

app/helpers/admin/cooking_posts_helper.rb
module Admin::CookingPostsHelper
end

app/views/admin/cooking_posts/_show.html.erb
<!--部分テンプレート：料理投稿詳細-->

<div class="col-4 text-right">
  <div><%= image_tag cooking_post.get_cooking_post_image(200, 200) %></div>
</div>

<div class="col-8">
  <div class="row pb-2">
    <div class="col-2 text-right"><strong>料理名</strong></div>
    <div class="col-3"><%= cooking_post.name %></div>
    <div class="col-2 text-right"><strong>投稿者</strong></div>
    <div class="col-3"><%= customer.name %></div>
  </div>

  <div class="row pb-2">
    <div class="col-2 text-right"><strong>紹介文</strong></div>
    <div class="col-8" style="height: auto;"><%= simple_format(cooking_post.introduction) %></div> <!--入力時の改行を反映-->
  </div>

  <% if customer == current_customer %> <!--ログインユーザーが投稿者なら表示-->
    <div class="row pt-2 pb-2">

      <div class="col-10 text-center">
        <div style="display: inline-block;">
          <%= link_to "編集する", edit_cooking_post_path(cooking_post), class: "btn btn-outline-success", style: "font-weight: bold;" %>
        </div>
        <div class="ml-5" style="display: inline-block;">
          <%= button_to "削除する", cooking_post_path(cooking_post), method: :delete, class: "btn btn-danger", data: {confirm: '本当に削除しますか？'} %>
        </div>
      </div>

    </div>
  <% end %>

</div>

app/views/admin/cooking_posts/index.html.erb
<!--料理投稿一覧ページ 26P-->
<div class="container">

  <div class="row pt-5">
    <div class="col-md-5 text-center">
      <h4 class="d-inline px-3" style="background-color: #dfdfdf;"><strong>料理投稿一覧</strong></h4>
    </div>
  </div>

  <div class="row my-4">
    <div class="col-md-9 mx-auto">
      <div class="table-responsive">
        <table class="table">
          <thead class="font-weight-bold" style="background-color: #dfdfdf;">
            <tr class="text-center">
              <th>レシピID</th>
              <th>画像</th>
              <th>料理名</th>
              <th>投稿者</th>
            </tr>
          </thead>
          <tbody>
            <% @cooking_posts.each do |cooking_post| %>
              <tr class="text-center">
                <td><%= cooking_post.id %></td>
                <td><%= image_tag cooking_post.get_cooking_post_image(70, 70) %></td>
                <td>
                  <%= link_to admin_cooking_post_path(cooking_post), style: "color: black; text-decoration: underline;" do %>
                    <%= cooking_post.name %>
                  <% end %>
                </td>
                <td><%= cooking_post.customer.name %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>

  <!--ページネーション-->
  <div class="row">
    <div class="col">
      <%= paginate @cooking_posts, class: "pagination" %>
    </div>
  </div>

</div>

app/views/admin/cooking_posts/show.html.erb
<!--料理投稿詳細ページ 27P-->
<div class="container">

  <div class="row pt-5">
    <div class="col-md-5 text-center">
      <h4 class="d-inline px-3" style="background-color: #dfdfdf;"><strong>料理投稿詳細</strong></h4>
    </div>
  </div>

  <!--部分テンプレート：料理投稿詳細-->
  <div class="row pt-3">
    <%= render 'show', cooking_post: @cooking_post, customer: @customer  %>
  </div>

</div>