config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords], controllers: { #skipで使わないルーティング削除
    sessions: "admin/sessions"
  }

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  #会員側の設定
  root 'public/homes#top'
  get 'about', to: 'public/homes#about'

  devise_scope :customer do #ゲストログイン機能
    post 'customer/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  scope module: :public do
    resources :cooking_posts, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      collection do #オリジナルのアクションに対する設定
        get 'search' #キーワード検索のアクション
      end
    end
    resources :food_strage_areas, only: [:index]
    resources :home_foods, only: [:new, :create, :index, :edit, :update, :destroy] do
      collection do
        get 'genre_search' #ジャンル検索のアクション
      end
    end

    get '/notifications/:id/mark_as_read' => 'notifications#mark_as_read', as: "mark_as_read_notifications" #URIパターンを設計書通りに修正
    resources :notifications, only: [:index, :destroy]

    get '/customers' => 'customers#index'
    get '/customers/my_page' => 'customers#show'
    get '/customers/information/edit' => 'customers#edit'
    patch '/customers/information' => 'customers#update'
    get '/customers/:id/cooking_posts' => 'customers#posts_index', as: "posts_index_customers"
    get '/customers/check' => 'customers#check'
    patch '/customers/out' => 'customers#out'
    get '/customers/search' => 'customers#search' #キーワード検索のアクション
  end

  #管理者側の設定
  get 'admin', to: 'admin/homes#top'
  namespace :admin do
    resources :genres, only: [:index, :destroy, :create, :edit, :update]
    resources :food_strage_areas, only: [:new, :create, :index, :destroy, :edit, :update]
    resources :cooking_posts, only: [:index, :show]

    get 'customers/:id/cooking_posts' => 'customers#posts_index', as: "customers_posts_index"
    resources :customers, only: [:show, :edit, :update]
  end

end

app/models/customer.rb
class Customer < ApplicationRecord

  before_validation :normalize_email  #データが保存される前にprivateで定義したメソッドを実行

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  #アソシエーション
  has_many :cooking_posts, dependent: :destroy
  has_many :notifications, dependent: :destroy
  has_many :home_foods, dependent: :destroy

  #バリデーション設定
  validates :name, presence: true
  validates :name_kana, presence: true
  validates :telephone_number, uniqueness: true, presence: true #uniqueness：一意性があるか
  validates :email, presence: true, uniqueness: true,
            format: { with: URI::MailTo::EMAIL_REGEXP }, #標準的なメールアドレスの形式に対し十分なバリデーションを提供
              unless: :guest? #ゲストログイン時はメールアドレスの一意性バリデーションを無効化（private内のメソッド実行）

  def active_for_authentication? #有効会員かどうかを判断
    super && (self.is_active == true)
  end

  #ゲストログイン機能
  def self.guest
    find_or_create_by!(email: "guest@example.com") do |customer| #emailが記述と一致する顧客レコードをデータベースから検索し、なかったら新しく作成
      customer.password = SecureRandom.urlsafe_base64 #ランダムな文字列を生成
      customer.name = "ゲストユーザー"
      #バリデーションで全カラムに対し空白がNGとなっているため、以下も設定しておく
      customer.name_kana = "ゲストユーザー"
      customer.telephone_number = '00000000000'
      customer.password_confirmation = customer.password
      customer.is_active = true
    end
  end

  private

  #emailの正規化処理
  def normalize_email
    self.email = email.downcase.strip if email.present? #email属性が存在する場合、emailの値を小文字に変換し両端の空白を削除
  end

  #ゲストユーザーかどうか判断
  def guest?
    email == "guest@example.com"
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  #管理者ログイン前ユーザーによるURL直打ちでの、ページ遷移と処理を制限（全てのアクションに対し）
  before_action :authenticate_admin!

  def posts_index
    @customer = Customer.find(params[:id])
    @cooking_posts = @customer.cooking_posts #会員に紐づく料理投稿を取得（idで指定された会員の投稿のみ表示するため定義）

    @customers = Customer.all.page(params[:page]).per(10) #ページネーション用に定義
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      flash[:notice] = "会員情報が更新されました"
      redirect_to admin_customer_path(@customer)

    else
      # 他のユーザーで同じメールアドレスまたは電話番号が存在しているか確認し、重複してたらそれぞれの変数に代入（where.not(id: @customer.id) ==> 現在のユーザー以外で）
      email_exists = Customer.where.not(id: @customer.id).exists?(email: customer_params[:email])
      telephone_exists = Customer.where.not(id: @customer.id).exists?(telephone_number: customer_params[:telephone_number])

      if email_exists && telephone_exists # メールアドレスと電話番号の両方が重複してたら
        flash.now[:alert] = "このメールアドレスと電話番号は既に使用されています"

      elsif email_exists # メールアドレスのみ重複してたら
        flash.now[:alert] = "このメールアドレスは既に使用されています"

      elsif telephone_exists # 電話番号のみ重複してたら
        flash.now[:alert] = "この電話番号は既に使用されています"

      else
        flash.now[:alert] = "入力項目を正しく入力してください"
      end
      render :edit
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:name, :name_kana, :telephone_number, :email, :is_active)
  end

end

app/controllers/pubic/customers_controller.rb
class Pubic::CustomersController < ApplicationController
  def index
  end

  def posts_index
  end

  def show
  end

  def edit
  end

  def update
  end

  def check
  end

  def out
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/pubic/customers_helper.rb
module Pubic::CustomersHelper
end

app/views/admin/customers/_show.html.erb
<!--部分テンプレート：会員情報詳細(プロフィール)-->

<% if admin_signed_in? %> <!--管理者がサインインしてる場合のみ表示-->
  <div class="row pt-3 pb-2">
    <div class="col-5 text-right offset-1"><strong>会員ID</strong></div>
    <div class="col-5 p-0" style="height: auto;"><%= customer.id %></div>
  </div>

  <div class="row pb-2">
    <div class="col-5 text-right offset-1"><strong>氏名</strong></div>
    <div class="col-5 p-0" style="height: auto;"><%= customer.name %></div>
  </div>

<% else %><!--余白の関係で氏名を場合分けに-->
  <div class="row pt-3 pb-2">
    <div class="col-5 text-right offset-1"><strong>氏名</strong></div>
    <div class="col-5 p-0" style="height: auto;"><%= customer.name %></div>
  </div>
<% end %>

<div class="row pb-2">
  <div class="col-5 text-right offset-1"><strong>フリガナ</strong></div>
  <div class="col-5 p-0" style="height: auto;"><%= customer.name_kana %></div>
</div>

<div class="row pb-2">
  <div class="col-5 text-right offset-1"><strong>メールアドレス</strong></div>
  <div class="col-5 p-0" style="height: auto;"><%= customer.email %></div>
</div>

<div class="row pb-2">
  <div class="col-5 text-right offset-1"><strong>電話番号</strong></div>
  <div class="col-5 p-0" style="height: auto;"><%= customer.telephone_number %></div>
</div>

<% if admin_signed_in? %> <!--管理者がサインインしてる場合のみ表示-->
  <div class="row pb-2">
    <div class="col-5 text-right offset-1"><strong>会員ステータス</strong></div>
    <% if customer.is_active == true %> <!--会員ステータスが有効なら-->
      <div class="col-5 p-0 text-success font-weight-bold" style="height: auto;">有効</div>
    <% else %>
      <div class="col-5 p-0 text-danger font-weight-bold" style="height: auto;">退会</div>
    <% end %>
  </div>

  <div class="row pt-2 pb-2">
    <div class="col-6 text-right">
      <%= link_to "編集する", edit_admin_customer_path(customer), class: "btn btn-outline-success", style: "font-weight: bold;" %>
    </div>
    <div class="col-6 text-left">
      <%= link_to "投稿一覧を見る", admin_customers_posts_index_path(customer), class: "btn btn-outline-primary", style: "font-weight: bold;" %>
    </div>
  </div>

<% else %>
  <div class="row pt-2 pb-2">
    <div class="col-4 offset-4 text-center"><%= link_to "編集する", customers_information_edit_path, class: "btn btn-outline-success", style: "font-weight: bold;" %></div>
  </div>
<% end %>

app/views/admin/customers/edit.html.erb
<!--会員情報編集ページ 24P-->
<div class="container">

  <div class="row pt-5">
    <div class="col-md-5 text-center">
      <h4 class="d-inline px-3" style="background-color: #dfdfdf;"><strong><%= @customer.name %>さんの会員情報編集</strong></h4>
    </div>
  </div>

  <%= form_with model: @customer, url: admin_customer_path do |f| %>

    <div class="row pt-3 pb-2">
      <div class="col-4 text-right offset-1"><%= f.label :"会員ID" %></div>
      <div class="col-5 p-0"><%= @customer.id %></div>
    </div>

    <div class="row pb-2">
      <div class="col-4 text-right offset-1"><%= f.label :"氏名" %></div>
      <div class="col-5 p-0"><%= f.text_field :name, required: true, autofocus: true %></div>
    </div>

    <div class="row pb-2">
      <div class="col-4 text-right offset-1"><%= f.label :"フリガナ" %></div>
      <div class="col-5 p-0"><%= f.text_field :name_kana, required: true %></div>
    </div>

    <div class="row pb-2">
      <div class="col-4 text-right offset-1"><%= f.label :"メールアドレス" %></div>
      <div class="col-5 p-0"><%= f.email_field :email, required: true %></div>
    </div>

    <div class="row pb-2">
      <div class="col-4 text-right offset-1"><%= f.label :"電話番号" %></div>
      <div class="col-5 p-0"><%= f.text_field :telephone_number, required: true %></div>
    </div>

    <div class="row pb-2">
      <div class="col-4 text-right offset-1"><%= f.label :"会員ステータス" %></div>
      <div class="col-5 p-0">
        <%= f.radio_button :is_active, true, checked: @customer.is_active == true %> <!--ラジオボタン-->
        <%= f.label :is_active, '有効' %> <!--ラベル-->
        <%= f.radio_button :is_active, false, checked: @customer.is_active == false %> <!--ラジオボタン-->
        <%= f.label :is_active, '退会' %> <!--ラベル-->
      </div>
    </div>

    <div class="row pt-2 pb-2">
      <div class="col-6 text-right"><%= f.submit "変更を保存", class: "btn btn-success", style: "font-weight: bold;" %></div>
    </div>

  <% end %>

</div>

app/views/admin/customers/posts_index.html.erb
<!--特定の会員の投稿一覧ページ 25P-->
<div class="container">

  <div class="row pt-5">
    <div class="col-md-5 text-center">
      <h4 class="d-inline px-3" style="background-color: #dfdfdf;"><strong><%= @customer.name %>さんの投稿一覧</strong></h4>
    </div>
  </div>

  <div class="row my-4">
    <div class="col-md-9 mx-auto">
      <div class="table-responsive">
        <table class="table">
          <thead class="font-weight-bold" style="background-color: #dfdfdf;">
            <tr class="text-center">
              <th>画像</th>
              <th>料理名</th>
            </tr>
          </thead>
          <tbody>
            <% @cooking_posts.each do |cooking_post| %>
              <tr class="text-center">
                <td><%= image_tag cooking_post.get_cooking_post_image(70, 70) %></td>
                <td>
                  <%= link_to admin_cooking_post_path(cooking_post.id), style: "color: black; text-decoration: underline;" do %>
                    <%= cooking_post.name %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>

  <!--ページネーション-->
  <div class="row">
    <div class="col">
      <%= paginate @customers, class: "pagination" %>
    </div>
  </div>

</div>

app/views/admin/customers/show.html.erb
<!--会員情報詳細ページ 23P-->
<div class="container">

  <div class="row pt-5">
    <div class="col-md-5 text-center">
      <h4 class="d-inline px-3" style="background-color: #dfdfdf;"><strong><%= @customer.name %>さんの会員詳細</strong></h4>
    </div>
  </div>

  <!--部分テンプレート：会員情報詳細(プロフィール)-->
  <%= render 'show', customer: @customer %>

</div>