config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords], controllers: { #skipで使わないルーティング削除
    sessions: "admin/sessions"
  }

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  #会員側の設定
  root 'public/homes#top'
  get 'about', to: 'public/homes#about'

  devise_scope :customer do #ゲストログイン機能
    post 'customer/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  scope module: :public do
    resources :cooking_posts, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      collection do #オリジナルのアクションに対する設定
        get 'search' #キーワード検索のアクション
      end
    end
    resources :food_strage_areas, only: [:index]
    resources :home_foods, only: [:new, :create, :index, :edit, :update, :destroy] do
      collection do
        get 'genre_search' #ジャンル検索のアクション
      end
    end

    get '/notifications/:id/mark_as_read' => 'notifications#mark_as_read', as: "mark_as_read_notifications" #URIパターンを設計書通りに修正
    resources :notifications, only: [:index, :destroy]

    get '/customers' => 'customers#index'
    get '/customers/my_page' => 'customers#show'
    get '/customers/information/edit' => 'customers#edit'
    patch '/customers/information' => 'customers#update'
    get '/customers/:id/cooking_posts' => 'customers#posts_index', as: "posts_index_customers"
    get '/customers/check' => 'customers#check'
    patch '/customers/out' => 'customers#out'
    get '/customers/search' => 'customers#search' #キーワード検索のアクション
  end

  #管理者側の設定
  get 'admin', to: 'admin/homes#top'
  namespace :admin do
    resources :genres, only: [:index, :destroy, :create, :edit, :update]
    resources :food_strage_areas, only: [:new, :create, :index, :destroy, :edit, :update]
    resources :cooking_posts, only: [:index, :show]

    get 'customers/:id/cooking_posts' => 'customers#posts_index', as: "customers_posts_index"
    resources :customers, only: [:show, :edit, :update]
  end

end

app/models/food_strage_area.rb
class FoodStrageArea < ApplicationRecord

  #バリデーション設定
  validates :name, uniqueness: true, presence: true #同じ食材を別々で登録しないため一意性を設定
  validates :place, presence: true

  enum place: {冷凍庫:0, 冷蔵庫:1, 常温:2}

end

app/controllers/admin/food_strage_areas_controller.rb
class Admin::FoodStrageAreasController < ApplicationController

  #管理者ログイン前ユーザーによるURL直打ちでの、ページ遷移と処理を制限（全てのアクションに対し）
  before_action :authenticate_admin!

  def new
    @food_strage_area = FoodStrageArea.new
  end

  def create
    @food_strage_area = FoodStrageArea.new(food_strage_area_params)
    if @food_strage_area.save
      flash[:notice] = "新しい食材を登録しました"
      redirect_to admin_food_strage_areas_path
    else
      flash.now[:alert] = "食材の登録ができませんでした"
      render :new
    end
  end

  def index
    @food_strage_areas = FoodStrageArea.all.page(params[:page]).per(10)
  end

  def destroy
    @food_strage_area = FoodStrageArea.find(params[:id])
    if @food_strage_area.destroy
      flash[:notice] = "食材保存場所が削除されました"
      redirect_to admin_food_strage_areas_path
    else
      flash[:notice] = "食材保存場所の削除の削除ができませんでした"
      redirect_to admin_food_strage_areas_path
    end
  end

  def edit
    @food_strage_area = FoodStrageArea.find(params[:id])
  end

  def update
    @food_strage_area = FoodStrageArea.find(params[:id])
    if @food_strage_area.update(food_strage_area_params)
      flash[:notice] = "食材保存場所情報が更新されました"
      redirect_to admin_food_strage_areas_path
    else
      @food_strage_area = FoodStrageArea.find(params[:id]) #renderでeditページを描くため、editで使う変数をこのアクション内で再定義
      flash.now[:alert] = "入力項目を正しく入力してください"
      render :edit
    end
  end

  private

  def food_strage_area_params
    params.require(:food_strage_area).permit(:name, :place)
  end

end

app/helpers/admin/food_strage_areas_helper.rb
module Admin::FoodStrageAreasHelper
end

app/views/admin/food_strage_areas/_index.html.erb
<!--部分テンプレート：食材保存場所一覧-->

<div class="table-responsive">
  <table class="table">
    <thead class="font-weight-bold" style="background-color: #dfdfdf;">
      <tr class="text-center">
        <th>食材名</th>
        <th>保存場所</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% food_strage_areas.each do |food_strage_area| %>
        <tr class="text-center">
          <td><%= food_strage_area.name %></td>
          <td><%= food_strage_area.place %></td>

          <% if admin_signed_in? %> <!--管理者がサインインしてる場合のみ表示-->
            <td>
              <div style="display: inline-block;">
                <%= link_to "編集", edit_admin_food_strage_area_path(food_strage_area), class: "btn btn-sm btn-outline-success", style: "font-weight: bold;" %>
              </div>
              <div class="ml-3" style="display: inline-block;">
                <%= button_to "削除", admin_food_strage_area_path(food_strage_area), method: :delete, class: "btn btn-sm btn-danger", data: {confirm: '本当に削除しますか？'} %>
              </div>
            </td>
          <% end %>

        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/food_strage_areas/_pagenation.html.erb
<!--部分テンプレート：ページネーション-->

<div style="display: flex; justify-content: center;">
  <%= paginate pages, class: "pagination" %>
</div>

app/views/admin/food_strage_areas/edit.html.erb
<!--食材保存場所編集ページ 30P-->
<div class="container">

  <div class="row pt-5">
    <div class="col-md-5 text-center">
      <h4 class="d-inline px-3" style="background-color: #dfdfdf;"><strong>食材保存場所の編集</strong></h4>
    </div>
  </div>

  <%= form_with model: @food_strage_area, url: admin_food_strage_area_path do |f| %>

    <div class="row pt-3 pb-2">
      <div class="col-3 text-right offset-1"><%= f.label :"食材名" %></div>
      <div class="col-5 p-0"><%= f.text_field :name, required: true, autofocus: true %></div>
    </div>

    <div class="row pb-2">
      <div class="col-3 text-right offset-1"><%= f.label :"保存場所" %></div>
      <div class="col-5 p-0">
        <% FoodStrageArea.places.keys.each do |place| %> <!--enumで定義した保存場所の値を取得し、ループでそれぞれの選択肢を生成-->
          <%= f.radio_button :place, place, id: "place_#{place}" %> <!--id: "place_#{place}" ラベルにもクリック判定をつけるため、ラジオボタンにid属性を付与-->
          <%= f.label :place, place, for: "place_#{place}" %> <!--for: "place_#{place}" ラベルにもクリック判定をつけるため、for属性で↑のidを指定-->
        <% end %>
      </div>
    </div>

    <div class="row pt-2 pb-2">
      <div class="col-3 offset-4 text-center"><%= f.submit "変更を保存", class: "btn btn-success", style: "font-weight: bold;" %></div>
    </div>

  <% end %>

</div>

app/views/admin/food_strage_areas/index.html.erb
<!--食材保存場所一覧ページ 28P-->
<div class="container">

  <div class="row pt-5">
    <div class="col-md-5 text-center">
      <h4 class="d-inline px-3" style="background-color: #dfdfdf;"><strong>食材保存場所一覧</strong></h4>
    </div>
  </div>

  <div class="row py-3">
    <div class="col-md-9 text-right">
      <%= link_to "新規登録", new_admin_food_strage_area_path, class: "btn btn-outline-success", style: "font-weight: bold;" %>
    </div>
  </div>

  <!--部分テンプレート：食材保存場所一覧-->
  <div class="row my-4">
    <div class="col-md-6 mx-auto">
      <%= render 'index', food_strage_areas: @food_strage_areas %>
    </div>
  </div>

  <!--ページネーション-->
  <div class="row">
    <div class="col">
      <%= paginate @food_strage_areas, class: "pagination" %>
    </div>
  </div>

</div>

app/views/admin/food_strage_areas/new.html.erb
<!--食材保存場所の新規登録ページ 29P-->
<div class="container">

  <div class="row pt-5">
    <div class="col-md-5 text-center">
      <h4 class="d-inline px-3" style="background-color: #dfdfdf;"><strong>食材保存場所の新規登録</strong></h4>
    </div>
  </div>

  <%= form_with model: @food_strage_area, url: admin_food_strage_areas_path do |f| %>

    <div class="row pt-3 pb-2">
      <div class="col-3 text-right offset-1"><%= f.label :"食材名" %></div>
      <div class="col-5 p-0"><%= f.text_field :name, required: true, autofocus: true, placeholder: "ピザチーズ" %></div>
    </div>

    <div class="row pb-2">
      <div class="col-3 text-right offset-1"><%= f.label :"保存場所" %></div>
      <div class="col-5 p-0">
        <% FoodStrageArea.places.keys.each do |place| %> <!--enumで定義した保存場所の値を取得し、ループでそれぞれの選択肢を生成-->
          <%= f.radio_button :place, place, id: "place_#{place}" %> <!--id: "place_#{place}" ラベルにもクリック判定をつけるため、ラジオボタンにid属性を付与-->
          <%= f.label :place, place, for: "place_#{place}" %> <!--for: "place_#{place}" ラベルにもクリック判定をつけるため、for属性で↑のidを指定-->
        <% end %>
      </div>
    </div>

    <div class="row pt-2 pb-2">
      <div class="col-3 offset-4 text-center"><%= f.submit "新規登録", class: "btn btn-success", style: "font-weight: bold;" %></div>
    </div>

  <% end %>

</div>