config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords], controllers: { #skipで使わないルーティング削除
    sessions: "admin/sessions"
  }

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  #会員側の設定
  root 'public/homes#top'
  get 'about', to: 'public/homes#about'

  devise_scope :customer do #ゲストログイン機能
    post 'customer/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  scope module: :public do
    resources :cooking_posts, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      collection do #オリジナルのアクションに対する設定
        get 'search' #キーワード検索のアクション
      end
    end
    resources :food_strage_areas, only: [:index]
    resources :home_foods, only: [:new, :create, :index, :edit, :update, :destroy] do
      collection do
        get 'genre_search' #ジャンル検索のアクション
      end
    end

    get '/notifications/:id/mark_as_read' => 'notifications#mark_as_read', as: "mark_as_read_notifications" #URIパターンを設計書通りに修正
    resources :notifications, only: [:index, :destroy]

    get '/customers' => 'customers#index'
    get '/customers/my_page' => 'customers#show'
    get '/customers/information/edit' => 'customers#edit'
    patch '/customers/information' => 'customers#update'
    get '/customers/:id/cooking_posts' => 'customers#posts_index', as: "posts_index_customers"
    get '/customers/check' => 'customers#check'
    patch '/customers/out' => 'customers#out'
    get '/customers/search' => 'customers#search' #キーワード検索のアクション
  end

  #管理者側の設定
  get 'admin', to: 'admin/homes#top'
  namespace :admin do
    resources :genres, only: [:index, :destroy, :create, :edit, :update]
    resources :food_strage_areas, only: [:new, :create, :index, :destroy, :edit, :update]
    resources :cooking_posts, only: [:index, :show]

    get 'customers/:id/cooking_posts' => 'customers#posts_index', as: "customers_posts_index"
    resources :customers, only: [:show, :edit, :update]
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>フードロス削減App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/44f448cde3.js" crossorigin="anonymous"></script> <!--FontAwesomeの導入-->
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header style="background-color: #e0e0e0; position: fixed; top: 0; left: 0; width: 100%; z-index: 1000;">

      <% if customer_signed_in? %> <!--会員がサインインしてる場合-->
        <!--ヘッダー上段-->
        <div class="px-3 py-2 border-bottom" style="border-bottom: 1px solid #404040 !important;">
          <div class="container">
            <div class="d-flex justify-content-between"> <!-- 左右に要素を分ける -->

              <!--ヘッダー上段の左側-->
              <div>
                <%= link_to root_path, style: "text-decoration: none; color: #404040;" do %>
                  <div style="display: inline-block; vertical-align: middle;">
                    <i class="fa-solid fa-utensils" style="font-size: 2em;"></i>
                  </div>
                  <div style="display: inline-block; vertical-align: middle; text-align: left; margin-left: 10px;">
                    <span>フードロス削減<br>アプリケーション</span>
                  </div>
                <% end %>
              </div>

              <!--ヘッダー上段の右側 -->
              <div class="d-flex"> <!--ul要素を右寄せにする-->
                <ul class="nav">
                  <% unless guest? %> <!--helpers/application_helper.rbに記述したメソッド呼び出し（ゲストユーザーでなければ表示）-->
                    <li class="nav-item mr-3">
                      <%= link_to notifications_path, style: "text-decoration: none; color: #404040;" do %>
                        <div style="text-align: center;">
                          <i class="fa-solid fa-bell" style="font-size: 2em;"></i>
                          <span style="display: block;">通知</span>
                        </div>
                      <% end %>
                    </li>
                    <li class="nav-item mr-3">
                      <%= link_to customers_my_page_path, style: "text-decoration: none; color: #404040;" do %>
                        <div style="text-align: center;">
                          <i class="fa-solid fa-circle-user" style="font-size: 2em;"></i>
                          <span style="display: block;">マイページ</span>
                        </div>
                      <% end %>
                    </li>
                  <% end %>
                  <li class="nav-item mr-3">
                    <%= link_to destroy_customer_session_path, method: :delete, style: "text-decoration: none; color: #404040;" do %>
                      <div style="text-align: center;">
                        <i class="fa-solid fa-right-from-bracket" style="font-size: 2em;"></i>
                        <span style="display: block;">ログアウト</span>
                      </div>
                    <% end %>
                  </li>
                </ul>
              </div>

            </div>
          </div>
        </div>

        <!--ヘッダー下段-->
        <div class="px-3 py-2 border-bottom" style="border-bottom: 1px solid #404040 !important;">
          <div class="container">
              <ul class="nav justify-content-center">
                <li class="nav-item"><%= link_to "食材保存場所一覧", food_strage_areas_path, class: "btn btn-outline-secondary mr-3" %></li>
                <li class="nav-item"><%= link_to "みんなの投稿一覧", cooking_posts_path, class: "btn btn-outline-secondary mr-3" %></li>
                <% unless guest? %> <!--helpers/application_helper.rbに記述したメソッド呼び出し（ゲストユーザーでなければ表示）-->
                  <li class="nav-item"><%= link_to "会員一覧", customers_path, class: "btn btn-outline-secondary mr-3" %></li>
                  <li class="nav-item"><%= link_to "自分の投稿一覧", posts_index_customers_path(current_customer.id), class: "btn btn-outline-secondary mr-3" %></li>
                  <li class="nav-item"><%= link_to "家庭内食材一覧", home_foods_path, class: "btn btn-outline-secondary mr-3" %></li>
                  <li class="nav-item"><%= link_to "料理の新規投稿", new_cooking_post_path, class: "btn btn-outline-secondary" %></li>
                <% end %>
              </ul>
          </div>
        </div>

      <% elsif admin_signed_in? %> <!--管理者がサインインしてる場合-->
        <!--ヘッダー上段-->
        <div class="px-3 py-2 border-bottom" style="border-bottom: 1px solid #404040 !important;">
          <div class="container">
            <div class="d-flex justify-content-between"> <!-- 左右に要素を分ける -->

              <!--ヘッダー上段の左側-->
              <div>
                <%= link_to admin_path, style: "text-decoration: none; color: #404040;" do %>
                  <div style="display: inline-block; vertical-align: middle;">
                    <i class="fa-solid fa-utensils" style="font-size: 2em;"></i>
                  </div>
                  <div style="display: inline-block; vertical-align: middle; text-align: left; margin-left: 10px;">
                    <span>フードロス削減<br>アプリケーション</span>
                  </div>
                <% end %>
              </div>

              <!--ヘッダー上段の右側 -->
              <div class="d-flex"> <!--ul要素を右寄せにする-->
                <ul class="nav">
                  <li><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "btn btn-outline-secondary" %></li>
                </ul>
              </div>

            </div>
          </div>
        </div>

        <!--ヘッダー下段-->
        <div class="px-3 py-2 border-bottom" style="border-bottom: 1px solid #404040 !important;">
          <div class="container">
              <ul class="nav justify-content-center">
                <li><%= link_to "会員一覧", admin_path, class: "btn btn-outline-secondary mr-3" %></li>
                <li><%= link_to "投稿一覧", admin_cooking_posts_path, class: "btn btn-outline-secondary mr-3" %></li>
                <li><%= link_to "食材保存場所一覧", admin_food_strage_areas_path, class: "btn btn-outline-secondary mr-3" %></li>
                <li><%= link_to "ジャンル一覧", admin_genres_path, class: "btn btn-outline-secondary mr-3" %></li>
              </ul>
          </div>
        </div>

      <% else %> <!--サインイン前の場合-->
        <!--ヘッダー上段-->
        <div class="px-3 py-2 border-bottom" style="border-bottom: 1px solid #404040 !important;">
          <div class="container">
            <div class="d-flex justify-content-between"> <!-- 左右に要素を分ける -->

              <!--ヘッダー上段の左側-->
              <div>
                <%= link_to root_path, style: "text-decoration: none; color: #404040;" do %>
                  <div style="display: inline-block; vertical-align: middle;">
                    <i class="fa-solid fa-utensils" style="font-size: 2em;"></i>
                  </div>
                  <div style="display: inline-block; vertical-align: middle; text-align: left; margin-left: 10px;">
                    <span>フードロス削減<br>アプリケーション</span>
                  </div>
                <% end %>
              </div>

              <!--ヘッダー上段の右側 -->
              <div class="d-flex"> <!--ul要素を右寄せにする-->
                <ul class="nav">
                  <li class="nav-item mr-3">
                    <%= link_to about_path, style: "text-decoration: none; color: #404040;" do %>
                      <div style="text-align: center;">
                        <i class="fa-solid fa-circle-info" style="font-size: 2em;"></i>
                        <span style="display: block;">About</span>
                      </div>
                    <% end %>
                  </li>
                  <li class="nav-item mr-3">
                    <%= link_to new_customer_registration_path, style: "text-decoration: none; color: #404040;" do %>
                      <div style="text-align: center;">
                        <i class="fa-solid fa-user-plus" style="font-size: 2em;"></i>
                        <span style="display: block;">新規登録</span>
                      </div>
                    <% end %>
                  </li>
                  <li class="nav-item mr-3">
                    <%= link_to new_customer_session_path, style: "text-decoration: none; color: #404040;" do %>
                      <div style="text-align: center;">
                        <i class="fa-solid fa-right-to-bracket" style="font-size: 2em;"></i>
                        <span style="display: block;">ログイン</span>
                      </div>
                    <% end %>
                  </li>
                </ul>
              </div>

            </div>
          </div>
        </div>
      <% end %>

    </header>

    <main style="margin-top: 150px;">
      <!--フラッシュメッセージ表示-->
      <% flash.each do |message_type, message| %>
        <div class="flash-message <%= message_type %>"><%= message %></div>
      <% end %>

      <!--各ページのビュー表示-->
      <%= yield %>
    </main>

    <footer>
      <div class="container-fluid mt-5" style="border-top: 2px double;">
        <div class="text-center text-muted" style="margin: 10px 0;">© 2024 M-MOCHI</div>
      </div>
    </footer>
  </body>
</html>